### PR TITLE
Added RelayDemo

### PR DESCRIPTION
**Pull request by HighKeys**
Hi there,

I added a simple Relay Demo Scene, check it out, should work if your project is connected and Relay is enabled in UGS Dashboard.

I didn't managed to update the package.json properly to include the samples as described here: https://docs.unity3d.com/Manual/cus-samples.html

Let me know if I should change something

BR
HighKeys

### CODE REVIEW

**Comment by ooonush** [comment]
Thank you! I'll take your pull request, and make some changes to it if you don't mind.

**Comment by HighKeys** [comment]
Sure! We just got many questions regarding Relay usage with your transport, so i thought i may add a quick and dirty example to the repo :)

Thanks for your work!

**Comment by ooonush** [comment]
I still think to create a separate repository for sample projects, or at least a separate folder in this repository because I do not want to clutter this package.

**Comment by HighKeys** [comment]
Oh i just checked the new Readme, looks awesome and should cover everything.. i will close the PR with that comment.

Btw just for future samples, you can add samples to the package.json and then ppl have to explicit import the sample project from Unity PackageManager. Here is the Reference from the unity docs: https://docs.unity3d.com/Manual/cus-samples.html

**Pull request closed without merging**
